service:
  image: fnetobr/tomcat8-probe
  container_name: tomcat8-probe1
  ports:
    - 18081:8080
  volumes:
    - ~/docker-files:/tmp/docker_files
    - ~/docker-files/tomcat8-probe/logs:/usr/local/tomcat/logs